dist: xenial

language: python

python:
- '3.6'

before_install:
  - pip install --user codecov
  - openssl aes-256-cbc -K $encrypted_d384cc2dd081_key -iv $encrypted_d384cc2dd081_iv
    -in id_rsa.enc -out id_rsa -d

install: pip install -r requirements.txt

script: pytest -v --cov . --cov-report term-missing --cov-fail-under=100 --flake8

after_success:
  - codecov --file coverage/lcov.info --disable search

deploy:
  skip_cleanup: true
  provider: script
  script: fab -i id_rsa -H root@165.22.77.77 deploy
  on:
    branch: master
