dist: xenial
language: python
python:
- '3.6'
before_install:
- openssl aes-256-cbc -K $encrypted_ce8296e67f8a_key -iv $encrypted_ce8296e67f8a_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
install: pip install -r requirements.txt
script: pytest -v --cov . --cov-report term-missing --flake8
deploy:
  skip_cleanup: true
  provider: script
  script: fab -H root@165.22.77.77 deploy
  on:
    branch: master
