dist: xenial

language: python

python:
- '3.6'

install: pip install -r requirements.txt

script: pytest -v --cov . --cov-report term-missing --flake8

deploy:
  skip_cleanup: true
  provider: script
  script: fab -H root@165.22.77.77 deploy
  on:
    branch: master